In [2]:
import torch
torch.__version__

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
#Scalar
scalar = torch.tensor(7)
scalar
scalar.ndim

tensor(7)

0

In [4]:
#Vector
vector = torch.tensor([1,2,3])
vector
vector.ndim
vector.shape

tensor([1, 2, 3])

1

torch.Size([3])

In [5]:
#matrix
matrix = torch.tensor([[1,2],[3,4]])
matrix
matrix.ndim
matrix.shape

tensor([[1, 2],
        [3, 4]])

2

torch.Size([2, 2])

In [6]:
#tensor
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor
tensor.ndim
tensor.shape
tensor[0][0][0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

3

torch.Size([1, 3, 3])

tensor(1)

In [7]:
#tensor
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
tensor
tensor.ndim
tensor.shape
tensor[0][0][0]

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

3

torch.Size([2, 3, 3])

tensor(1)

In [8]:
randon_tensor = torch.rand([2,2,2])
randon_tensor
randon_tensor.dtype

tensor([[[0.4697, 0.3435],
         [0.4252, 0.8486]],

        [[0.2115, 0.5231],
         [0.7223, 0.4112]]])

torch.float32

In [9]:
randon_img_tensor = torch.rand([224,224,3])
randon_img_tensor.dtype
size = randon_img_tensor.shape
size[0]
size[1]
size[2]

torch.float32

224

224

3

In [10]:
zero_tensor = torch.zeros([2,2,2])
zero_tensor

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [11]:
arrange_tensor = torch.arange(0,9,1)
arrange_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
float_32_tensor = torch.tensor([1.0,2,3], dtype=torch.float16, device=None, requires_grad=False)
float_32_tensor
float_32_tensor.dtype
float_32_tensor.device

tensor([1., 2., 3.], dtype=torch.float16)

torch.float16

device(type='cpu')

In [17]:
tensor = torch.tensor([1,2,3])
tensor += 10
tensor *= 2
tensor

tensor([22, 24, 26])

In [22]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1,2,3])
t1 * t2
torch.matmul(t1,t2)
t1 @ t2

tensor([1, 4, 9])

tensor(14)

tensor(14)

In [24]:
%%time
t1 @ t2

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [25]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [28]:
tensor_A @ tensor_B.T
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [29]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [31]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
x.argmax()
x.argmin()

Minimum: 0
Maximum: 90


tensor(9)

tensor(0)

In [57]:
x = torch.arange(0,9,1)
x.shape
x.ndim
x_reshaped = x.reshape(1,9)
x_reshaped.ndim

torch.Size([9])

1

2

In [58]:
x_stacked = torch.stack([x,x,x], dim=0)
x_stacked
x_stacked = torch.stack([x,x,x], dim=1)
x_stacked


tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]])

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8]])

In [60]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
New shape: torch.Size([9])


In [61]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Previous shape: torch.Size([9])

New tensor: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])
New shape: torch.Size([1, 9])


In [62]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [63]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [64]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [68]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [70]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array
tensor

array([1., 2., 3., 4., 5., 6., 7.])

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [72]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor
numpy_tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [73]:
!nvidia-smi

Sat Apr 27 00:40:18 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.79                 Driver Version: 537.79       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro P1000                 WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   49C    P8              N/A / ERR! |    465MiB /  4096MiB |     11%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [78]:
# Check for GPU
if torch.cuda.is_available():
    # Set device type
    device = "cuda" if torch.cuda.is_available() else "cpu"
    device
    # Count number of devices
    torch.cuda.device_count()

'cuda'

1

In [81]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [83]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu
tensor_on_gpu

array([1, 2, 3], dtype=int64)

tensor([1, 2, 3], device='cuda:0')